# general
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top
set -g mouse on

# vim navigation
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key C-h resize-pane -L 5
bind-key C-j resize-pane -D 5
bind-key C-k resize-pane -U 5
bind-key C-l resize-pane -R 5

# bindings for lazygit and dotfiles 
bind g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit"
bind d display-menu -T "#[align=centre].dotfiles" -x C -y C \
  "starship.toml"     s  "display-popup -E 'nvim ~/.config/starship.toml'" \
  ".tmux.conf"        t  "display-popup -E 'nvim ~/.tmux.conf'" \
  ".zshrc"            z  "display-popup -E 'nvim ~/.zshrc'" \
  "Quit"              q  ""

# minimal status bar
set -g status-style bg=default
set -g status-justify left
set -g status-left ""
set -g status-right-length 200
set -g status-right "#[bg=default,fg=#8a5a5a]tmux #[fg=red]#S  #{W:#[fg=#9a9a9a]#[bold]#I#[nobold] #{b:pane_current_path} #[fg=#6a6a6a]#{pane_current_command}  ,#[fg=#7aff7a]#[bold]#I#[nobold] #{b:pane_current_path} #[fg=#e6c84a]#{pane_current_command}  }"
set -g window-status-format ""
set -g window-status-current-format ""

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
run '~/.tmux/plugins/tpm/tpm'
